---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


#### Loading and preprocessing the data
```{r, echo=TRUE}
getwd()
document <- read.csv("activity.csv", header = TRUE, sep = ",")
# Brief analysis of the data
class(document)
dim(document)
str(document)
summary(document)
head(document)
# Review if there are some missing values and how many
sum(is.na(document))
mean(is.na(document))

# The class of the variable 'date' is Factor. I change it to Date class
document$date <- as.Date(document$date, format = "%Y-%m-%d")
class(document$date)
```

#### What is mean total number of steps taken per day?
```{r, echo=TRUE}
# Total numbers taken per day
steps_byDay <- aggregate(steps ~ date, data = document, sum)
summary(steps_byDay)
steps_byDay

# Histogram
hist(steps_byDay$steps, main = "Steps per day", xlab = "Steps", ylim = c(0, 15), col = "purple", breaks = seq(0, 25000, by = 1000))
dev.copy(png, "Plot_Question_1.png", height = 480, width = 480)
dev.off()

# mean and median of the total number of steps taken per day
mean_byDay <- mean(steps_byDay$steps, na.rm = TRUE)
mean_byDay
median_byDay <- median(steps_byDay$steps, na.rm = TRUE)
median_byDay
```

#### What is the average daily activity pattern?
```{r, echo=TRUE}
# series plot (i.e.type="l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
interval_mean <- aggregate(steps ~ interval, data = document, mean, na.rm = TRUE)
plot(interval_mean$interval, interval_mean$steps, type = "l", col = "purple", xlim = c(0, 2500), main = "Average daily", xlab = "Interval", ylab = "Steps mean")
dev.copy(png, "Plot_Question_2.png", height = 480, width = 480)
dev.off()

# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
max_steps <- interval_mean[which.max(interval_mean$steps),]$interval
max_steps
```
#### Imputing missing values
```{r, echo=TRUE}
# Total number of missing values in the dataset (i.e. the total number of rows with NAs
null_rows <- sum(is.na(document$steps))
null_rows

# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

# For this question, I have created a new column that include the mean of each interval by any value of 'steps' = NA
document$imputSteps <- ifelse(is.na(document$steps), interval_mean$steps[match(document$interval, interval_mean$interval)], document$steps)

# Create a new dataset that is equal to the original dataset but with the missing data filled in.
completeDocument <- data.frame(steps = document$imputSteps, interval = document$interval, date = document$date)

# histogram of the total number of steps taken each day.
steps_byDayComplet <- aggregate(steps ~ date, data = completeDocument, sum)
hist(steps_byDayComplet$steps, main = "Steps per day complete", xlab = "Steps", ylim = c(0, 20), col = "purple", breaks = seq(0, 25000, by = 1000))
dev.copy(png, "Plot_Question_3.png", height = 480, width = 480)
dev.off()

# Calculate and report the mean and median total number of steps taken per day.
mean_byDayComplet <- mean(steps_byDayComplet$steps, na.rm = TRUE)
mean_byDayComplet
median_byDayComplete <- median(steps_byDayComplet$steps, na.rm = TRUE)
median_byDayComplete

# Do these values differ from the estimates from the first part of the assignment? 
# What is the impact of imputing missing data on the estimates of the total daily number of steps?

# By changing the group we can see that there are very few changes in the mean value. The 1000 range is slightly higher, changes from about 10 frequencies to about 18
```


#### Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day
str(completeDocument)
# I have already change the class of date variable in the beginning of this exercice. 

# Now we need identify what name of the day are each date. To do this I apply the function 'weekday()'
completeDocument$day_name <- weekdays(completeDocument$date)

# Once we have the names by each date, we have to create a new variable to classify and group by 'weekend' or 'weekday'
completeDocument$type_of_day <- ifelse(completeDocument$day_name == "sábado" | completeDocument$day_name == "domingo", "Weekend", "Weekday")

# Plot containing a time series plot (i.e.type="l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

# I have created two groups, one per type of day 'weekend' and the other with 'weekday'
weekend <- subset(completeDocument, type_of_day == "Weekend")
weekday <- subset(completeDocument, type_of_day == "Weekday")
# Now I calculate the mean by each group created
average_weekend <- aggregate(steps ~ interval, data = weekend, mean, na.rm = TRUE)
average_weekday <- aggregate(steps ~ interval, data = weekday, mean, na.rm = TRUE)

# Then I apply the 'par()' function to represent the layout for both plots together
par(mfrow = c(2, 1), mar = c(4, 4, 4, 1))
plot(average_weekend$interval, average_weekend$steps, type = "l", ylim = c(0, 250), ylab = "Frequency_weekend", xlab = "Interval", main = "Weekend", col = "purple")
plot(average_weekday$interval, average_weekday$steps, type = "l", ylim = c(0, 250), ylab = "Frequency_weekday", xlab = "Interval", main = "Weekday", col = "purple")
dev.copy(png, "Plot_Question_4.png", height = 480, width = 480)
dev.off()
```


